// Test data with names, codes, and prices
export const testData = [
  { name: "Complete Blood Count (CBC)", code: "CBC001", price: 250 },
  { name: "Widal", code: "WID001", price: 100 },
  { name: "Blood Sugar Fasting", code: "BSF002", price: 60 },
  { name: "Blood Sugar Random", code: "BSR003", price: 50 },
  { name: "HbA1c (Glycated Hemoglobin)", code: "HBA004", price: 500 },
  { name: "Lipid Profile", code: "LIP005", price: 500 },
  { name: "Liver Function Test (LFT)", code: "LFT006", price: 500 },
  { name: "Kidney Function Test (KFT)", code: "KFT007", price: 500 },
  { name: "Thyroid Function Test (TFT)", code: "TFT008", price: 400 },
  { name: "Vitamin D", code: "VTD009", price: 1500 },
  { name: "Vitamin B12", code: "VTB010", price: 1000 },
  { name: "Iron Studies", code: "IRN011", price: 250 },
  { name: "Urine Routine", code: "URN012", price: 100 },
  { name: "ECG", code: "ECG013", price: 150 },
  { name: "Chest X-Ray", code: "CXR014", price: 0 },
  { name: "Ultrasound Abdomen", code: "USA015", price: 0 },
  { name: "Typhi DOT (Rapid)", code: "TYD016", price: 200 },
  { name: "MP (Card)", code: "MPC017", price: 200 },
  { name: "Dengue Ns1", code: "DNS018", price: 600 },
  { name: "Blood Group", code: "BLG019", price: 50 },
  { name: "HBTCDC", code: "HTC021", price: 150 },
  { name: "MP (Malaria Parasites)", code: "MPM022", price: 200 },
  { name: "ESR", code: "ESR023", price: 100 },
  { name: "Bio-Chemistry Report (Full)", code: "BCR024", price: 0 },
  { name: "Widal (Table)", code: "WDT025", price: 0 },
  { name: "VDRL Report", code: "VDR026", price: 100 },
  { name: "RA q", code: "RAQ028", price: 400 },
  { name: "CRP", code: "CRP029", price: 400 },
  { name: "CRPQ", code: "CRQ030", price: 400 },
  { name: "KFTfull", code: "KFT031", price: 500 },
  { name: "RFT", code: "RFT032", price: 500 },
  { name: "HIV-I-II", code: "HIV033", price: 350 },
  { name: "Uric Acid", code: "URA034", price: 150 },
  { name: "S. Creatinine", code: "SCR035", price: 150 },
  { name: "Blood Sugar Analysis", code: "BSA036", price: 50 },
  { name: "FPP", code: "FPP037", price: 120 },
  { name: "COVID-19", code: "CVD039", price: 1000 },
  { name: "Prostate Test", code: "PRT040", price: 0 },
  { name: "Scrub Typhus (Anti Body)", code: "SCT041", price: 800 },
  { name: "D-Dimer", code: "DDM042", price: 1500 },
  { name: "Antenatal Profile", code: "ANP043", price: 1250 },
  { name: "Stool Examination", code: "STE001", price: 70 },
  { name: "Serum Creatinine", code: "SRC002", price: 150 },
  { name: "LDH", code: "LDH003", price: 350 },
  { name: "Sputum Examination", code: "SPT004", price: 100 },
  { name: "Blood Sugar (R)", code: "BSR005", price: 50 },
  { name: "Blood Sugar (F)", code: "BSF006", price: 100 },
  { name: "TB IGM & TB IGG - ELISA", code: "TBI007", price: 0 },
  { name: "HBSAG", code: "HBS008", price: 150 },
  { name: "D3", code: "D3T009", price: 1450 },
  { name: "Tuberculin Test", code: "TBT010", price: 200 },
  { name: "Covid Mini", code: "CVM011", price: 3000 },
  { name: "Chikungunya", code: "CHK012", price: 800 },
  { name: "Serum Electrolytes", code: "SRE013", price: 500 },
  { name: "X-Ray", code: "XRY014", price: 0 },
  { name: "ANC Telang", code: "ANC015", price: 1300 },
  { name: "Ultra Sonography", code: "ULT016", price: 0 },
  { name: "Semen Full", code: "SMN017", price: 100 },
  { name: "Bilirubin Total", code: "BLR018", price: 150 },
  { name: "Seminal Fluid Report [After Wash]", code: "SFR019", price: 0 },
  { name: "Prothrombin Time", code: "PRT020", price: 150 },
  { name: "Fasting Sugar", code: "FAS021", price: 60 },
  { name: "Prostate Profile", code: "PRP022", price: 200 },
  { name: "Troponin-T", code: "TRP023", price: 1000 },
  { name: "Pancreas Function Test", code: "PFT024", price: 0 },
  { name: "HBV Single", code: "HBV025", price: 650 },
  { name: "Serology", code: "SRL026", price: 700 },
  { name: "Malaria Card Test", code: "MCT027", price: 200 },
  { name: "Fluid Report", code: "FLR028", price: 300 },
  { name: "Dengue IGG & IGM", code: "DNG029", price: 800 },
  { name: "Blood Culture & Sensitivity Report", code: "BCS030", price: 300 },
  { name: "Serum Amylase", code: "SRA032", price: 400 },
  { name: "A.F.B. Study", code: "AFB033", price: 200 },
  { name: "A.S.O. Titre", code: "ASO034", price: 0 },
  { name: "Adenosine Deaminase Study", code: "ADS035", price: 0 },
  { name: "Allergy Profile", code: "ALP036", price: 3600 },
  { name: "Anaemia Profile", code: "ANP037", price: 0 },
  { name: "Anti HCV", code: "AHC038", price: 300 },
  { name: "Anti Thyroid Antibody", code: "ATA039", price: 0 },
  { name: "Antidengue Antibody", code: "ADA040", price: 0 },
  { name: "Creatine Kinase", code: "CRK041", price: 0 },
  { name: "Ascitic Fluid", code: "ASF042", price: 0 },
  { name: "Culture & Sensitivity Study-2", code: "CSS043", price: 0 },
  { name: "Autoimmune Profile", code: "AIP044", price: 0 },
  { name: "C.S.F. Study", code: "CSF045", price: 0 },
  { name: "C3 & C4 Complement Level", code: "CCL046", price: 0 },
  { name: "Calcium Estimation", code: "CAE047", price: 100 },
  { name: "Cardiac Profile", code: "CAP048", price: 0 },
  { name: "Coagulation Profile", code: "COP049", price: 0 },
  { name: "G6 PD Enzyme", code: "G6P050", price: 150 },
  { name: "Culture & Sensitivity Report", code: "CSR051", price: 300 },
  { name: "Culture & Sensitivity Study", code: "CST052", price: 0 },
  { name: "Antilupus Anticoagulant", code: "ALA053", price: 0 },
  { name: "Widal Reaction", code: "WDR054", price: 0 },
  { name: "High Sensitiv C.R.P.", code: "HSC055", price: 0 },
  { name: "Amylase", code: "AMY056", price: 250 },
  { name: "S.G.O.T.", code: "SGT057", price: 90 },
  { name: "Throat Swab Study", code: "TSS058", price: 100 },
  { name: "Tumor Markars", code: "TUM059", price: 0 },
  { name: "Urinary Microalbumin", code: "URM060", price: 0 },
  { name: "Sodium", code: "SOD061", price: 100 },
  { name: "Creatinine", code: "CRT062", price: 150 },
  { name: "Special Investigation", code: "SPI063", price: 0 },
  { name: "Urine for B.J. Proteins", code: "UBJ064", price: 100 },
  { name: "Serum Magnesium", code: "SRM065", price: 150 },
  { name: "Serum Lipase", code: "SRL066", price: 400 },
  { name: "Phosphorus", code: "PHS067", price: 200 },
  { name: "TSH", code: "TSH068", price: 200 },
  { name: "Ferritin", code: "FER069", price: 800 },
  { name: "TuberTT", code: "TBT070", price: 200 },
  { name: "IL-6 (Interleukin-6)", code: "IL6071", price: 2800 },
  { name: "UPT", code: "UPT072", price: 150 },
  { name: "Biltab", code: "BLT076", price: 30 },
  { name: "Ammonia Level", code: "AML078", price: 400 },
  { name: "CPK", code: "CPK079", price: 350 },
  { name: "Alkaline Phosphate", code: "ALP080", price: 90 },
  { name: "24 Hrs. Urine Microalbumin", code: "URM081", price: 0 },
  { name: "Urine Albumin Report", code: "UAR082", price: 20 },
  { name: "VM Profile", code: "VMP083", price: 0 },
  { name: "Cyto Breast Mastitis", code: "CBM084", price: 202 },
  { name: "Vitamins", code: "VIT085", price: 0 },
  { name: "Enzyme Estimations", code: "ENZ087", price: 0 },
  { name: "Electrolytes", code: "ELY088", price: 250 },
  { name: "Direct Coom's Test", code: "DCT089", price: 100 },
  { name: "Culture & Sensitivity Study-3", code: "CSS090", price: 0 },
  { name: "Dilantin", code: "DIL091", price: 0 },
  { name: "Cyto Cold Abscess", code: "CCA092", price: 0 },
  { name: "Dengue Virus", code: "DNG093", price: 600 },
  { name: "CSF (Cerebro-Spinal Fluid Report)", code: "CSF094", price: 2500 },
  { name: "Ear Scapping Stduy", code: "ERS095", price: 100 },
  { name: "Ascitic Fluid Study", code: "AFS096", price: 0 },
  { name: "Urine Pregnancy Test", code: "UPT129", price: 150 },
  { name: "C. Reactive Protein (C.R.P.)", code: "CRP130", price: 400 },
  { name: "RA-ASO-CRP", code: "RAC131", price: 200 },
  { name: "BTCT", code: "BTC132", price: 100 },
  { name: "SGOT", code: "SGT133", price: 100 },
  { name: "Blood Urea", code: "BLU135", price: 100 },
  { name: "Hemoglobin", code: "HGB136", price: 50 },
  { name: "SGPT", code: "SGP137", price: 150 },
  { name: "Urine Culture", code: "URC138", price: 600 },
  { name: "S. Sodium/Potassium/Chloride", code: "SPC139", price: 750 },
  { name: "S. Cholesterol", code: "SCH140", price: 200 },
  { name: "S. Alkaline phosphatase", code: "SAP141", price: 100 },
  { name: "Total Protein", code: "TPR142", price: 100 },
  { name: "S. Calcium", code: "SCA143", price: 150 },
  { name: "Glucose Tolerance Test", code: "GTT144", price: 0 },
  { name: "FSH/LH", code: "FSH145", price: 1000 },
  { name: "GBP", code: "GBP147", price: 200 },
  { name: "PTTK / (aPTT)", code: "PTK148", price: 500 },
  { name: "Beta HCG", code: "BHC149", price: 0 },
  { name: "AEC", code: "AEC150", price: 150 },
  { name: "Semen (IUI)", code: "SMN151", price: 250 },
  { name: "Pre-Operative Profile", code: "POP153", price: 500 },
  { name: "Urine Analysis", code: "URA154", price: 100 },
  { name: "TORCH", code: "TOR155", price: 700 },
  { name: "OTprofile", code: "OTP156", price: 1500 },
  { name: "Toxo Pregnancy Test", code: "TXP157", price: 80 },
  { name: "Toxo Plazma", code: "TXZ158", price: 0 },
  { name: "Fertility Profile", code: "FRP159", price: 1000 },
  { name: "Urine Analysis (New)", code: "UAN160", price: 100 },
  { name: "Haeomgram (CBC)", code: "HGM162", price: 250 },
];

